<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\protosets.json" />
      <EmbeddedResource Include="Resources\powerusage.json" />
      <EmbeddedResource Include="Resources\protosets.json" />
    </ItemGroup>

</Project>
