name: Deploy bpx.mbwarez.dk

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Setup .NET
        uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3
        with:
          dotnet-version: 9.0.x

      - name: Publish
        run: dotnet publish -c Release -o dist

      - name: Deploy to GitHub Pages (other repo via SSH)
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: lordmike/bpx.mbwarez.dk
          publish_dir: ./dist/wwwroot
          publish_branch: main
          cname: bpx.mbwarez.dk
